// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKEGDp86C-HIK7xdB8UH9QxsH_8VXSNg',
    appId: '1:616163291315:android:ce0718028e1a9af079c0c6',
    messagingSenderId: '616163291315',
    projectId: 'vegieapps',
    databaseURL: 'https://vegieapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vegieapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlqmSc7X6PC9mtb4EnVdr3ZaLPoA1pUqA',
    appId: '1:616163291315:ios:0ae31ad2eef0883279c0c6',
    messagingSenderId: '616163291315',
    projectId: 'vegieapps',
    databaseURL: 'https://vegieapps-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vegieapps.appspot.com',
    iosBundleId: 'com.alfathoshi.bintangMotioninternWeek7',
  );
}
